// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: delete_feedFollow_by_user_and_url.sql

package database

import (
	"context"
)

const deleteFeedFollowByUrlAndName = `-- name: DeleteFeedFollowByUrlAndName :exec
DELETE FROM feed_follows
WHERE feed_id IN (SELECT f.id FROM feeds f WHERE f.url = $1)
AND user_id IN (SELECT u.id FROM users u WHERE u.name = $2)
`

type DeleteFeedFollowByUrlAndNameParams struct {
	Url  string
	Name string
}

func (q *Queries) DeleteFeedFollowByUrlAndName(ctx context.Context, arg DeleteFeedFollowByUrlAndNameParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollowByUrlAndName, arg.Url, arg.Name)
	return err
}
